services:
  web-app:
    build:
      context: ./backend/autoCheck
    ports:
      - "8000:8000"
    volumes:
      - ./backend/autoCheck:/autoCheck
    
    environment:
      - DB_HOST=database
      - DB_NAME=autocheckdb
      - DB_USER=postgres
      - DB_PASS=postgres

    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    
    depends_on:
      - database
      - redis

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=autocheckdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  react-app:
    image: docker-react-i
    build:
      context: ./client/
    volumes:
      - react_build:/react/build
  
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
     - web-app
     - react-app
volumes:
  react_build: