# Generated by Django 4.2.8 on 2024-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.CharField(choices=[('site_side', 'site_side'), ('equal', 'equal'), ('user_side', 'user_side')], default='site_side', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(unique=True)),
                ('operation_type', models.CharField(choices=[('Bonus', 'bonus'), ('Withdraw', 'withdraw'), ('Payment', 'payment')], max_length=8)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
