# Generated by Django 4.2.8 on 2024-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='users/avatar/default-avatar.png', upload_to='users/avatar/'),
        ),
    ]
