# Generated by Django 5.0 on 2023-12-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_network',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'Youtube'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('vk', 'VK'), ('viber', 'Viber')], max_length=30),
        ),
    ]
