# Generated by Django 5.0 on 2023-12-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('users', 'Users'), ('reviews', 'Reviews'), ('referral', 'Referral'), ('violators', 'Violators'), ('ticket', 'Ticket'), ('history', 'History')], max_length=9)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
