# Generated by Django 5.0 on 2023-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_contact_email_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffplan',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
